name: Analyze & Test

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: unit test
        run: |
          yarn
          yarn build
          yarn lint
        env:
          CI: true